### PR TITLE
Add `check-release` workflow on CI

### PR DESCRIPTION
**Pull request by jtpio**
To be able to start publishing the package to PyPI.

### CODE REVIEW

**Comment by jtpio** [comment]
CI all green.

**Comment by jtpio** [comment]
@Zsailer would it be possible to add me to the PyPI project? https://pypi.org/project/notebook-shim/

To be able to create a new token for the releaser.

Thanks!

**Comment by Zsailer** [comment]
Yep! Done 😎 

FYI, this pypi package currently has releases of an older version of the shim (one that I wrote before nbclassic existed). We can start from v0.1.0 with this new iteration.

**Comment by jtpio** [comment]
Yes the version has been properly reset to `0.1.0` in this PR.

**Comment by jtpio** [comment]
Moving forward with this since CI is all green.

**Pull request merged**
